---
- hosts: web
  tasks:
        - name: "Stop existing app if any"
          command: forever stopall

        - name: "Start example Node.js app."
          command: forever start /home/cloudwiki/bin/www
