---
- hosts: web
  tasks:
        - name: "Stop existing app if any"
          command: forever stopall

        - name: "Start example Node.js app."
          command: forever start /home/cloudwiki/bin/www

        # added bellow task to reboot node service
       # - name: restart node server
       #   service: name=cloudwiki enabled=yes state=restarted
